// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace HospitalManagementSystem2.Models;

public partial class StaffSchedule
{
    public int Id { get; set; }

    public int ScheduleId { get; set; }

    public int StaffId { get; set; }
    public bool IsDeleted { get; set; }

    public virtual Schedule Schedule { get; set; }

    public virtual Staff Staff { get; set; }
}